#!/bin/sh

set -e -u

DUMMY_PRINTER_NAME=adt-printer0

# Create dummy printer
/usr/sbin/lpadmin -p $DUMMY_PRINTER_NAME -E -v file:///dev/null

# Print the default testprint to it
/usr/bin/lp -d $DUMMY_PRINTER_NAME /usr/share/cups/data/testprint

# Delete it
/usr/sbin/lpadmin -x $DUMMY_PRINTER_NAME
