#! /bin/sh

set -e

case "$1" in
    configure)
        if [ -z "`getent group lpadmin`" ]; then
            addgroup --system lpadmin
        fi

	chown root:lpadmin /usr/bin/lppasswd
	chmod u+s /usr/bin/lppasswd
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

#DEBHELPER#

exit 0


